# EDA Practice

## Vectorization

In [1]:
import numpy as np

# NumPy ML Challenge 33: Vectorization (No Loops)

## Dataset
ages = np.array([15, 18, 22, 35, 60, 12, 45, 28])

### Task 1
Increase every age by **1 year**.

### Task 2
Find all adults (**age >= 18**).

### Task 3
Create a binary label array.
Rules:

- Age < 18 → 0
- Age >= 18 → 1

### Task 4
Calculate the average age of adults only.

### Task 5
Calculate:

- Number of adults
- Number of minors

### Task 6 (ML-Oriented)
Create age groups using **np.where()**.

Rules:

- Age < 18 → "Minor"
- 18 <= Age <= 40 → "Adult"
- Age > 40 → "Senior"



In [9]:
ages = np.array([15, 18, 22, 35, 60, 12, 45, 28])

new_ages=ages+1

mask_adults=ages>=18
adults=ages[mask_adults]

labels=np.where(ages<18, 0, 1)

avg_adult_age=np.mean(adults)

adult_count=len(adults)


minor_count=len(ages)-len(adults)

# Define your list of conditions in order
conditions = [(ages < 18),(ages >= 18) & (ages <= 40),(ages > 40)]
choices = ["Minor", "Adults", "Senior"]
age_group = np.select(conditions, choices, default="Unknown")




print("New Ages:")
print(new_ages)

print("\nAdults:")
print(adults)

print("\nLabels:")
print(labels)

print("\nAverage Adult Age:")
print(avg_adult_age)

print("\nAdult Count:")
print(adult_count)

print("\nMinor Count:")
print(minor_count)

print("\nAge Groups:")
print(age_group)

New Ages:
[16 19 23 36 61 13 46 29]

Adults:
[18 22 35 60 45 28]

Labels:
[0 1 1 1 1 0 1 1]

Average Adult Age:
34.666666666666664

Adult Count:
6

Minor Count:
2

Age Groups:
['Minor' 'Adults' 'Adults' 'Adults' 'Senior' 'Minor' 'Senior' 'Adults']


# NumPy ML Challenge 34: Broadcasting Basics

## Dataset


marks = np.array([
    [80, 75, 90],
    [60, 85, 70],
    [95, 88, 92],
    [72, 68, 80]
])

bonus = np.array([5, 2, 3])


## Tasks

### Task 1
Add the bonus marks to every student.

**Store in:** `updated_marks`

### Task 2
Calculate the average marks of every student.

**Store in:** `student_average`

### Task 3
Calculate the average marks of every subject.

**Store in:** `subject_average`

### Task 4
Find the topper (student index) based on the average marks.

**Store in:** `topper_index`

### Task 5
Normalize each subject independently.

Formula:

\[
\frac{x-\mu}{\sigma}
\]

Normalize **column-wise**.

**Store in:** `normalized_marks`

In [19]:
marks = np.array([ [80, 75, 90], 
                   [60, 85, 70],
                   [95, 88, 92],
                   [72, 68, 80] ])

bonus = np.array([5, 2, 3])

updated_marks=marks+bonus
print(updated_marks)
student_average=np.mean(updated_marks, axis=1)
print(student_average)
subject_average=np.mean(updated_marks, axis=0)
print(subject_average)
topper_index=np.argmax(student_average)
print(topper_index)
avg=np.mean(updated_marks, axis=0)
std_d=np.std(updated_marks, axis=0)
normalized_marks=(updated_marks-avg)/std_d
print(normalized_marks)

[[ 85  77  93]
 [ 65  87  73]
 [100  90  95]
 [ 77  70  83]]
[85.         75.         95.         76.66666667]
[81.75 81.   86.  ]
2
[[ 0.25559075 -0.50196464  0.79772404]
 [-1.31727542  0.75294697 -1.48148749]
 [ 1.43524038  1.12942045  1.02564519]
 [-0.37355572 -1.38040277 -0.34188173]]


# NumPy ML Challenge 35: Broadcasting with Column Vectors

## Dataset

```python
import numpy as np

sales = np.array([
    [120, 150, 180],
    [200, 210, 220],
    [160, 170, 180],
    [300, 310, 320]
])

discount = np.array([
    [10],
    [20],
    [15],
    [30]
])
```

## Tasks

### Task 1
Subtract the discount from each row using broadcasting.

**Store in:** `final_sales`

### Task 2
Calculate the total sales of each store after the discount.

**Store in:** `store_total`

### Task 3
Calculate the average sales of each product after the discount.

**Store in:** `product_average`

### Task 4
Find the index of the store with the highest total sales.

**Store in:** `best_store`

### Task 5
Normalize each product (column-wise).

Formula:

`(final_sales - mean) / std`

**Store in:** `normalized_sales`

In [24]:
sales = np.array([
    [120, 150, 180],
    [200, 210, 220],
    [160, 170, 180],
    [300, 310, 320]
])

discount = np.array([
    [10],
    [20],
    [15],
    [30]
])

final_sales=sales-discount
store_total=np.sum(final_sales, axis=1)
product_average=np.mean(final_sales, axis=0)
best_store=np.argmax(store_total)
avg=np.mean(final_sales, axis=0)
std_d=np.std(final_sales, axis=0)
normalized_sales=(final_sales-avg)/std_d

print(final_sales)
print(store_total)
print(product_average)
print(best_store)
print(normalized_sales)


[[110 140 170]
 [180 190 200]
 [145 155 165]
 [270 280 290]]
[420 570 465 840]
[176.25 191.25 206.25]
3
[[-1.11314082 -0.9428402  -0.72252059]
 [ 0.06300797 -0.0229961  -0.12457252]
 [-0.52506643 -0.66688697 -0.8221786 ]
 [ 1.57519928  1.63272328  1.66927171]]



# NumPy ML Challenge 36: Broadcasting with Row Vectors

## Dataset

```python
prices = np.array([
    [100, 200, 300],
    [150, 250, 350],
    [200, 300, 400],
    [250, 350, 450]
])

tax_rate = np.array([1.05, 1.12, 1.18])
```

## Tasks

### Task 1
Apply the tax rate to each product using broadcasting.

**Store in:** `final_prices`

### Task 2
Calculate the total bill for each customer.

**Store in:** `customer_total`

### Task 3
Calculate the average price of each product after tax.

**Store in:** `product_average`

### Task 4
Find the customer who paid the highest total bill.

**Store in:** `highest_customer`

### Task 5
Find the most expensive product on average after tax.

**Store in:** `most_expensive_product`

In [31]:
prices = np.array([
    [100, 200, 300],
    [150, 250, 350],
    [200, 300, 400],
    [250, 350, 450]
])

tax_rate = np.array([1.05, 1.12, 1.18])

final_prices=prices+prices*tax_rate/100
customer_total=np.sum(final_prices, axis=1)
product_average=np.mean(final_prices, axis=0)
highest_customer=np.argmax(customer_total)
most_expensive_product=np.argmax(product_average)
print(final_prices)
print(customer_total)
print(product_average)
print(highest_customer)
print(most_expensive_product)

[[101.05  202.24  303.54 ]
 [151.575 252.8   354.13 ]
 [202.1   303.36  404.72 ]
 [252.625 353.92  455.31 ]]
[ 606.83   758.505  910.18  1061.855]
[176.8375 278.08   379.425 ]
3
2


# NumPy ML Challenge 37: Double Broadcasting

## Dataset

```python
import numpy as np

scores = np.array([
    [50, 60, 70],
    [80, 90, 100],
    [65, 75, 85]
])

bonus = np.array([[5], [10], [15]])

multiplier = np.array([1.0, 1.1, 1.2])
```

## Tasks

### Task 1
Add the bonus to each student's scores.

**Store in:** `bonus_scores`

### Task 2
Multiply each subject by the corresponding multiplier.

**Store in:** `final_scores`

### Task 3
Calculate the average score of each student.

**Store in:** `student_average`

### Task 4
Calculate the average score of each subject.

**Store in:** `subject_average`

### Task 5
Find the student with the highest average score.

**Store in:** `top_student`

In [36]:
scores = np.array([
    [50, 60, 70],
    [80, 90, 100],
    [65, 75, 85]
])

bonus = np.array([[5], [10], [15]])

multiplier = np.array([1.0, 1.1, 1.2])

bonus_scores=scores+bonus
final_scores=bonus_scores*multiplier
student_average=np.mean(final_scores, axis=1)
subject_average=np.mean(final_scores, axis=0)
top_student=np.argmax(student_average)



print(bonus_scores)
print(final_scores)
print(student_average)
print(subject_average)
print(top_student)

[[ 55  65  75]
 [ 90 100 110]
 [ 80  90 100]]
[[ 55.   71.5  90. ]
 [ 90.  110.  132. ]
 [ 80.   99.  120. ]]
[ 72.16666667 110.66666667  99.66666667]
[ 75.   93.5 114. ]
1


# NumPy ML Challenge 38: Broadcasting Rules

## Dataset

```python
import numpy as np

A = np.ones((3, 4))

B = np.array([10, 20, 30, 40])

C = np.array([
    [1],
    [2],
    [3]
])

D = np.array([5, 10])
```

## Tasks

### Task 1
Add `A` and `B`.

**Store in:** `result1`

### Task 2
Multiply `A` and `C`.

**Store in:** `result2`

### Task 3
Try to add `A` and `D`.

What happens?

### Task 4
Explain **why** Task 3 fails.

(No code required.)

### Task 5
Print the shapes of `A`, `B`, `C`, and `D`.

In [42]:
A = np.ones((3, 4))

B = np.array([10, 20, 30, 40])

C = np.array([
    [1],
    [2],
    [3]
])

D = np.array([5, 10])

print(np.shape(A))
print(np.shape(B))
print(np.shape(C))
print(np.shape(C))


result1=A+B
print(result1)
result2=A*C
print(result2)
result3=A+D      
print(result3)

 # Explaination :- The shape of A and B is not equal so 
# Gives an error:-  operands could not be broadcast together with shapes (3,4) (2,)

(3, 4)
(4,)
(3, 1)
(3, 1)
[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

# NumPy ML Challenge 39: Broadcasting Prediction

## Dataset

```python
import numpy as np

A = np.ones((2, 3))

B = np.array([10, 20, 30])

C = np.array([[5], [10]])

D = np.array([1, 2])

E = np.ones((2, 1))
```

## Tasks

For each operation:

1. Predict:
   - ✅ Works
   - ❌ Error

2. Explain why.

3. If it works, write the resulting shape.

### Task 1

`A + B`

### Task 2

`A + C`

### Task 3

`A + D`

### Task 4

`A + E`

### Task 5

Verify your predictions by running the code.

In [47]:
A = np.ones((2, 3))

B = np.array([10, 20, 30])

C = np.array([[5], [10]])

D = np.array([1, 2])

E = np.ones((2, 1))

# Works
print(A+B)
# because no of col of A nd B are same
print(np.shape(A+B))
# Works

print(A+C)
print(np.shape(A+C))
# Error
print(A+D)
# operands could not be broadcast together with shapes (2,3) (2,) 

# Works
print(A+E)
print(np.shape(A+E))

[[11. 21. 31.]
 [11. 21. 31.]]
[[ 5]
 [10]]
[[ 6.  6.  6.]
 [11. 11. 11.]]
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

# NumPy ML Challenge 40: Employee Salary Proces
sing

## Dataset

```python

salary = np.array([
    [25000, 5000, 2000],
    [30000, 6000, 2500],
    [28000, 5500, 2200],
    [35000, 7000, 3000]
])

increment = np.array([
    [1000],
    [1500],
    [1200],
    [2000]
])

tax_rate = np.array([0.90, 0.95, 1.00])
```

## Tasks

### Task 1
Add the increment to every employee's salary.

**Store in:** `updated_salary`

### Task 2
Apply the tax rate to every salary component using broadcasting.

**Store in:** `final_salary`

### Task 3
Calculate the total salary of each employee after applying the tax rate.

**Store in:** `employee_total`

### Task 4
Calculate the average salary of each salary component after applying the tax rate.

**Store in:** `component_average`

### Task 5
Find the index of the employee with the highest total salary.

**Store in:** `highest_paid_employee`

### Task 6
Normalize each salary component independently.

Formula:

`(final_salary - mean) / std`

Normalize **column-wise**.

**Store in:** `normalized_salary`

### Task 7 (Challenge)
Without using any loop, calculate the percentage contribution of each salary component to an employee's total salary.

Formula:

`(final_salary / employee_total.reshape(-1, 1)) * 100`

**Store in:** `salary_percentage`

In [11]:
salary = np.array([
    [25000, 5000, 2000],
    [30000, 6000, 2500],
    [28000, 5500, 2200],
    [35000, 7000, 3000]
])

increment = np.array([
    [1000],
    [1500],
    [1200],
    [2000]
])

tax_rate = np.array([0.90, 0.95, 1.00])

updated_salary=salary+increment

final_salary=updated_salary-(salary*tax_rate/100)

employee_total=np.sum(final_salary,axis=1)

component_average=np.mean(final_salary, axis=0)

highest_paid_employee=np.argmax(employee_total)

normalized_salary=(final_salary-component_average)/np.std(final_salary, axis=0)

reshaped_employee_total=employee_total.reshape(-1,1)
salary_percentage=(salary/reshaped_employee_total)*100
print(updated_salary)
print(final_salary)
print(employee_total)
print(component_average)
print(highest_paid_employee)
print(normalized_salary)
print(salary_percentage)

[[26000  6000  3000]
 [31500  7500  4000]
 [29200  6700  3400]
 [37000  9000  5000]]
[[25775.    5952.5   2980.  ]
 [31230.    7443.    3975.  ]
 [28948.    6647.75  3378.  ]
 [36685.    8933.5   4970.  ]]
[34707.5  42648.   38973.75 50588.5 ]
[30659.5     7244.1875  3825.75  ]
3
[[-1.22669909 -1.16497172 -1.12832963]
 [ 0.14327604  0.1793088   0.19911699]
 [-0.42982813 -0.53792641 -0.59735098]
 [ 1.51325117  1.52358932  1.52656362]]
[[72.03054095 14.40610819  5.76244328]
 [70.34327518 14.06865504  5.8619396 ]
 [71.84322781 14.11206261  5.64482504]
 [69.18568449 13.8371369   5.93020153]]


# NumPy ML Challenge 41: Why Vectorization is Fast

## Dataset

```python
import numpy as np

numbers = np.arange(1, 100001)
```

## Tasks

### Task 1
Calculate the square of every number using NumPy vectorization.

**Store in:** `squared`

---

### Task 2
Calculate the cube of every number using NumPy vectorization.

**Store in:** `cubed`

---

### Task 3
Create a new array containing only the even numbers.

**Store in:** `even_numbers`

---

### Task 4
Calculate the sum of all even numbers.

**Store in:** `even_sum`

---

### Task 5
Calculate the average of all squared values.

**Store in:** `average_square`

---

### Task 6
Without using any loop, create a label array using `np.where()`.

Rules:

- Square > 2,500,000,000 → `"Large"`
- Otherwise → `"Small"`

**Store in:** `labels`

---

### Task 7 (Conceptual)

Answer these questions:

1. Why is vectorized NumPy code much faster than a Python `for` loop?
2. When should you prefer vectorization over loops?

In [19]:
numbers = np.arange(1, 100001)
squared=numbers**2
print(squared)

cubed=numbers**3
print(cubed)

mask_even=numbers%2==0
even_numbers=numbers[mask_even]
print(even_numbers)

even_sum=np.sum(even_numbers)
print(even_sum)

average_square=np.mean(squared)
print(average_square)

labels=np.where(squared > 2500000000, "Large", "Small")
print(labels)




# QNS  Why is vectorized NumPy code much faster than a Python for loop?
# ---> because nupy uses in built functions of C and C is faster than Python


                                                       
# Qns  When should you prefer vectorization over loops?
# -->  Working with Large Datasets,Applying Grid Mathematics, linear algebra.Broadcasting Operations, etc

[          1           4           9 ...  9999600004  9999800001
 10000000000]
[               1                8               27 ...  999940001199992
  999970000299999 1000000000000000]
[     2      4      6 ...  99996  99998 100000]
2500050000
3333383333.5
['Small' 'Small' 'Small' ... 'Large' 'Large' 'Large']


# NumPy ML Challenge 42: Memory Sharing

## Dataset

```python
import numpy as np

data = np.array([10, 20, 30, 40, 50])
```

## Tasks

### Task 1
Create a **view** of `data`.

**Store in:** `view_data`

---

### Task 2
Change the second element of `view_data` to `999`.

Print both `data` and `view_data`.

---

### Task 3
Create a **copy** of `data`.

**Store in:** `copy_data`

---

### Task 4
Change the last element of `copy_data` to `555`.

Print both `data` and `copy_data`.

---

### Task 5
Use NumPy to check whether `view_data` shares memory with `data`.

**Hint:** There is a NumPy function for this.

**Store in:** `view_memory`

---

### Task 6
Use NumPy to check whether `copy_data` shares memory with `data`.

**Store in:** `copy_memory`

---

### Task 7 (Conceptual)

Answer:

1. When should you use `.view()`?
2. When should you use `.copy()`?

In [25]:
data = np.array([10, 20, 30, 40, 50])

view_data=data.view()
view_data[1]=999
print(data)
print(view_data)

copy_data=data.copy()
copy_data[-1]=555
print(data)
print(copy_data)

[ 10 999  30  40  50]
[ 10 999  30  40  50]
[ 10 999  30  40  50]
[ 10 999  30  40 555]


# NumPy ML Challenge 43: In-Place Operations

## Dataset

```python
import numpy as np

weights = np.array([2.5, 4.0, 6.5, 8.0, 10.5])
bias = 1.5
```

## Tasks

### Task 1

Increase every weight by the bias using an **in-place operation**.

**Store in:** `weights`

---

### Task 2

Multiply every weight by **2** using an **in-place operation**.

**Store in:** `weights`

---

### Task 3

Create a **new array** by dividing the updated weights by **2**.

**Store in:** `half_weights`

---

### Task 4

Check whether `half_weights` shares memory with `weights`.

**Store in:** `shares_memory`

---

### Task 5

Find:

- Maximum weight
- Minimum weight
- Average weight

Store in:

- `max_weight`
- `min_weight`
- `avg_weight`

---

### Task 6 (Conceptual)

Answer:

1. What is the difference between:

```python
weights = weights + 5
```

and

```python
weights += 5
```

2. Why are in-place operations preferred when working with very large datasets?

In [34]:
weights = np.array([2.5, 4.0, 6.5, 8.0, 10.5])
bias = 1.5
weights+=bias
print(weights)

weights*=2
print(weights)
half_weights/=2
print(half_weights)

shares_memory=np.shares_memory(weights, half_weights)
print(shares_memory)

w_max=np.max(weights)
w_min=np.min(weights)
w_mean=np.mean(weights)
print(w_max,w_min, w_mean)


# What is the difference between:
# weights = weights + 5
# and
# weights += 5

# Q1-->weights += 5    here we are using asigning operater and in other case we add 5 manualy bu addin in the same thing at the same time

#Why are in-place operations preferred when working with very large datasets?
# Q2--> they alter existing data directly without allocating memory for new copies

[ 4.   5.5  8.   9.5 12. ]
[ 8. 11. 16. 19. 24.]
[2.   2.75 4.   4.75 6.  ]
False
24.0 8.0 15.6


# NumPy ML Challenge 44: Efficient Indexing & Slicing

## Dataset

```python
import numpy as np

data = np.arange(1, 37).reshape(6, 6)
```

## Tasks

### Task 1

Extract the first three rows.

**Store in:** `top_rows`

### Task 2

Extract the last two columns.

**Store in:** `last_columns`

### Task 3

Extract the 3×3 center block.

**Store in:** `center_block`

### Task 4

Extract all even numbers from the matrix.

**Store in:** `even_numbers`

### Task 5

Replace every value greater than **25** with **-1**.

Do **not** use any loops.

**Store in:** `modified_data`

### Task 6 (Conceptual)

Answer:

1. Why is slicing generally faster than iterating through rows with a Python `for` loop?
2. Does slicing usually return a **view** or a **copy** in NumPy?

In [46]:
data = np.arange(1, 37).reshape(6, 6)

top_rows=data[0:3,:]
print(top_rows)

last_columns=data[:, 4:6]
print(last_columns)

center_block=data[2:5,2:5]
print(center_block)

mask_even=data%2==0
even_numbers=data[mask_even]
print(even_numbers)

modified_data=np.where(data>25, -1, data)
print(modified_data)

# Q1-->because of how NumPy handles memory and execution.
# Q2-->In NumPy, slicing almost always returns a view, not a copy.

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 5  6]
 [11 12]
 [17 18]
 [23 24]
 [29 30]
 [35 36]]
[[15 16 17]
 [21 22 23]
 [27 28 29]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]]


# NumPy ML Challenge 45: Student Performance Analysis

## Dataset

```python
import numpy as np

marks = np.array([
    [85, 90, 78],
    [70, 88, 92],
    [95, 76, 89],
    [60, 65, 72],
    [80, 84, 88]
])
```

## Tasks

### Task 1

Calculate the average marks of each student.

**Store in:** `student_average`

### Task 2

Calculate the average marks of each subject.

**Store in:** `subject_average`

### Task 3

Create a new array where:

- Average ≥ 85 → `"Excellent"`
- 75 ≤ Average < 85 → `"Good"`
- Average < 75 → `"Needs Improvement"`

Use only vectorized NumPy operations.

**Store in:** `performance`

### Task 4

Normalize every subject independently.

Formula:

```text
(value - mean) / std
```

Normalize **column-wise**.

**Store in:** `normalized_marks`

### Task 5

Find the topper (student index).

**Store in:** `topper`

### Task 6

Without using any loops, calculate the percentage contribution of each subject to a student's total marks.

Formula:

```python
(marks / total_marks.reshape(-1, 1)) * 100
```

**Store in:** `subject_percentage`

### Task 7 (Conceptual)

Answer:

1. Why is this solution considered efficient?
2. Which NumPy concepts from Phases 1–3 did you use?

In [65]:
marks = np.array([
    [85, 90, 78],
    [70, 88, 92],
    [95, 76, 89],
    [60, 65, 72],
    [80, 84, 88]
])
print(np.mean(marks, axis=1))
print(np.mean(marks, axis=0))
average=np.mean(marks, axis=1)
condition=[average >= 85, (75 <= average) & (average < 85), average < 75]
output=["Excellent", "Good", "Needs Improvement"]
print(np.select(condition, output, default=" "))

mean = np.mean(marks, axis=0)
std = np.std(marks, axis=0)  


scores_normalized = (marks - mean) / std

print(scores_normalized)
print(np.argmax(average))


total_marks = np.sum(marks, axis=1)
subject_percentage = (marks / total_marks.reshape(-1, 1)) * 100
print(subject_percentage)



# Q1,2 ---> it relies on vectorization and contiguous memory storage rather than slow, explicit Python loops

[84.33333333 83.33333333 86.66666667 65.66666667 84.        ]
[78.  80.6 83.8]
['Good' 'Good' 'Excellent' 'Needs Improvement' 'Good']
[[ 0.57932412  1.02660227 -0.76849846]
 [-0.66208471  0.80817625  1.08649783]
 [ 1.40693001 -0.50237983  0.68899862]
 [-1.4896906  -1.70372291 -1.56349687]
 [ 0.16552118  0.37132422  0.55649889]]
2
[[33.59683794 35.57312253 30.83003953]
 [28.         35.2        36.8       ]
 [36.53846154 29.23076923 34.23076923]
 [30.45685279 32.99492386 36.54822335]
 [31.74603175 33.33333333 34.92063492]]


# NumPy ML Challenge 46: Basic Feature Engineering

## Dataset

```python
import numpy as np

employees = np.array([
    [22, 25000],
    [35, 50000],
    [28, 32000],
    [45, 80000],
    [31, 45000]
])
```

### Columns

- Column 0 → Age
- Column 1 → Salary

## Tasks

### Task 1

Extract:

- `age`
- `salary`

---

### Task 2

Create a new feature:

**Salary per Age**

Formula:

```python
salary / age
```

Store in:

```python
salary_per_age
```

---

### Task 3

Create an age category.

Rules:

- Age < 25 → `"Young"`
- 25 ≤ Age < 40 → `"Adult"`
- Age ≥ 40 → `"Senior"`

Store in:

```python
age_category
```

---

### Task 4

Normalize the **salary** column only.

Formula:

```text
(value - mean) / std
```

Store in:

```python
normalized_salary
```

---

### Task 5

Create a binary feature:

Salary ≥ 40,000 → 1

Otherwise → 0

Store in:

```python
high_salary
```

---

### Task 6

Combine the original dataset with the new feature
`salary_per_age` as a new column.

**Hint:**

Use:

```python
np.column_stack()
```

Store in:

```python
new_dataset
```

---

### Task 7 (Conceptual)

Answer:

1. What is feature engineering?
2. Why can a newly created feature sometimes improve an ML model more than adding more data?

In [21]:
employees = np.array([
    [22, 25000],
    [35, 50000],
    [28, 32000],
    [45, 80000],
    [31, 45000]
])
# Column 0 → Age
# Column 1 → Salary

age=employees[:,0]
print(age)

salary=employees[:,1]
print(salary)

salary_per_age=salary/age
print(salary_per_age)

condition=[age < 25, (age>=25)&(age<40), age>=40]
output=["Young", "Adult", "Senior"]
age_category=np.select(condition, output, default=" ")
print(age_category)

avg=np.mean(salary)
stdd=np.std(salary)
normalized_salary=(salary-avg)/stdd
print(normalized_salary)

high_salary=np.where(salary>=40000, 1, 0)
print(high_salary)

new_dataset=np.column_stack((employees, salary_per_age))
print(new_dataset)



# Task 7
# Feature engineering is the process of using domain knowledge to select, transform, or create new input variables (features) from raw data so that machine learning algorithms can learn underlying patterns more effectively

[22 35 28 45 31]
[25000 50000 32000 80000 45000]
[1136.36363636 1428.57142857 1142.85714286 1777.77777778 1451.61290323]
['Young' 'Adult' 'Adult' 'Senior' 'Adult']
[-1.12500768  0.18925363 -0.75701451  1.76636719 -0.07359863]
[0 1 0 1 1]
[[2.20000000e+01 2.50000000e+04 1.13636364e+03]
 [3.50000000e+01 5.00000000e+04 1.42857143e+03]
 [2.80000000e+01 3.20000000e+04 1.14285714e+03]
 [4.50000000e+01 8.00000000e+04 1.77777778e+03]
 [3.10000000e+01 4.50000000e+04 1.45161290e+03]]


# NumPy ML Challenge 47: Multi-Feature Engineering

## Dataset

```python
import numpy as np

students = np.array([
    [18, 170, 65, 82],
    [20, 165, 72, 91],
    [19, 180, 80, 76],
    [21, 175, 68, 88],
    [22, 160, 55, 69]
])
```

### Columns

- Column 0 → Age (years)
- Column 1 → Height (cm)
- Column 2 → Weight (kg)
- Column 3 → Marks

---

## Tasks

### Task 1

Extract the following columns:

- `age`
- `height`
- `weight`
- `marks`

---

### Task 2

Create a new feature:

**BMI**

Formula:

```python
BMI = weight / (height_in_meters ** 2)
```

> Convert height from **cm** to **meters** before calculating BMI.

Store in:

```python
bmi
```

---

### Task 3

Create two categorical features.

#### Marks Category

- Marks ≥ 85 → `"Excellent"`
- 70 ≤ Marks < 85 → `"Good"`
- Marks < 70 → `"Average"`

Store in:

```python
marks_category
```

#### BMI Category

- BMI < 18.5 → `"Underweight"`
- 18.5 ≤ BMI < 25 → `"Normal"`
- BMI ≥ 25 → `"Overweight"`

Store in:

```python
bmi_category
```

---

### Task 4

Normalize **only** these columns:

- Height
- Weight
- Marks

Store in:

```python
normalized_features
```

---

### Task 5

Create a new dataset containing:

```
Age
Height
Weight
Marks
BMI
High Marks (1 if Marks ≥ 85 else 0)
```

Use:

```python
np.column_stack()
```

Store in:

```python
final_dataset
```

---

## Conceptual Questions

1. Why is BMI usually a better feature than using only height or only weight?
2. Which features in this dataset are:
   - Numerical
   - Binary
   - Categorical

In [37]:
students = np.array([
    [18, 170, 65, 82],
    [20, 165, 72, 91],
    [19, 180, 80, 76],
    [21, 175, 68, 88],
    [22, 160, 55, 69]
])

age=students[:,0]
height=students[:,1]
weight=students[:,2]
marks=students[:,3]

print(age)
print(height)
print(weight)
print(marks)

bmi = weight/ ((height/100)** 2)
print(bmi)

condition=[marks>=85, (marks>=70)&(marks<85), marks<70]
output=["Excellent", "Good", "Average"]
marks_category=np.select(condition, output, default=" ")
print(marks_category)

condition=[bmi<18.5, (bmi>=18.5)&(bmi<25), bmi<=25]
output=["Underweight", "Normal", "Overweight"]
bmi_category=np.select(condition, output, default=" ")
print(bmi_category)


height_norm =(height-np.mean(height))/np.std(height)
weight_norm =(weight-np.mean(weight))/np.std(weight)
marks_norm =(marks-np.mean(marks))/np.std(marks)
normalized_features=np.column_stack((height_norm, weight_norm, marks_norm))
print(normalized_features)

High_Marks=np.where(marks>=85, 1, 0)



final_dataset=np.column_stack((age, height, weight, marks, bmi, High_Marks))
print(final_dataset)


# Q1 --->BMI is a better feature than raw height or weight because it scales weight relative to height squared
# Q2 ---> Numerical

[18 20 19 21 22]
[170 165 180 175 160]
[65 72 80 68 55]
[82 91 76 88 69]
[22.49134948 26.44628099 24.69135802 22.20408163 21.484375  ]
['Good' 'Excellent' 'Good' 'Excellent' 'Average']
['Normal' ' ' 'Normal' 'Normal' 'Normal']
[[ 0.         -0.36487819  0.10018803]
 [-0.70710678  0.48650426  1.22730336]
 [ 1.41421356  1.45951277 -0.65122219]
 [ 0.70710678  0.          0.85159825]
 [-1.41421356 -1.58113883 -1.52786744]]
[[ 18.         170.          65.          82.          22.49134948
    0.        ]
 [ 20.         165.          72.          91.          26.44628099
    1.        ]
 [ 19.         180.          80.          76.          24.69135802
    0.        ]
 [ 21.         175.          68.          88.          22.20408163
    1.        ]
 [ 22.         160.          55.          69.          21.484375
    0.        ]]


# NumPy ML Challenge 48: Duplicate Detection & Data Cleaning

## Dataset

```python
import numpy as np

employees = np.array([
    [101, 25, 50000],
    [102, 30, 60000],
    [103, 28, 55000],
    [102, 30, 60000],
    [104, 35, 70000],
    [101, 25, 50000],
    [105, 40, 80000]
])
```

### Columns

- Employee ID
- Age
- Salary

## Tasks

### Task 1

Find all duplicate rows.

**Hint:** Use `np.unique()` with:

```python
axis=0
return_counts=True
```

Store:

- `unique_rows`
- `counts`

---

### Task 2

Print only the rows that appear more than once.

---

### Task 3

Create a dataset containing only unique employees.

Store in:

```python
cleaned_data
```

---

### Task 4

Calculate:

- Average Age
- Average Salary

using the cleaned dataset.

---

### Task 5

Normalize the Salary column of the cleaned dataset.

---

## Conceptual Questions

### Q1

Why should duplicate records usually be removed before training an ML model?

### Q2

What problems can duplicate rows cause during model training?

In [2]:
import numpy as np

employees = np.array([
    [101, 25, 50000],
    [102, 30, 60000],
    [103, 28, 55000],
    [102, 30, 60000],
    [104, 35, 70000],
    [101, 25, 50000],
    [105, 40, 80000]
])

unique_rows, counts = np.unique(employees, axis=0,return_counts=True)
duplicates = unique_rows[counts > 1]
print(unique_rows)
print(counts)

print(duplicates)

cleaned_data=np.unique(employees, axis=0)
print(cleaned_data)

print(np.mean(cleaned_data[: , 1]))
print(np.mean(cleaned_data[: , 2]))

norm_salary=(cleaned_data[:, 2]-np.mean(cleaned_data[: , 2]))/np.std(cleaned_data[: , 2])
print(norm_salary)

[[  101    25 50000]
 [  102    30 60000]
 [  103    28 55000]
 [  104    35 70000]
 [  105    40 80000]]
[2 2 1 1 1]
[[  101    25 50000]
 [  102    30 60000]]
[[  101    25 50000]
 [  102    30 60000]
 [  103    28 55000]
 [  104    35 70000]
 [  105    40 80000]]
31.6
63000.0
[-1.2070197  -0.27854301 -0.74278135  0.64993368  1.57841037]


# NumPy ML Challenge 49: Missing Values

## Dataset

```python
import numpy as np

marks = np.array([
    [85, np.nan, 78],
    [90, 88, np.nan],
    [np.nan, 76, 82],
    [95, 91, 89],
    [80, np.nan, np.nan]
])
```

### Columns

- Column 0 → Math
- Column 1 → Physics
- Column 2 → Chemistry

---

## Task 1

Find the location (row, column) of all missing values.

Store in:

```python
nan_locations
```

---

## Task 2

Count the total number of missing values.

Store in:

```python
total_nan
```

---

## Task 3

Calculate the mean of each subject **ignoring NaN values**.

Store in:

```python
subject_mean
```

---

## Task 4

Replace every NaN with the **mean of its respective column**.

> Do **not** use any loops.

Store in:

```python
cleaned_marks
```

**Hint:**

You may need:

```python
np.where()
np.isnan()
```

or advanced indexing.

---

## Task 5

Find students who still have **no missing values** after cleaning.

Store in:

```python
complete_students
```

---

## Task 6

Normalize every subject independently using the cleaned dataset.

Formula:

```text
(value - mean) / std
```

Store in:

```python
normalized_marks
```

---

## Conceptual Questions

### Q1

Why is `np.mean()` not suitable for datasets containing NaN values?

### Q2

Why is replacing missing values with the **column mean** usually better than replacing them with 0?

### Q3

In which situations would you **remove** rows containing NaN instead of filling them?

In [31]:
marks = np.array([
    [85, np.nan, 78],
    [90, 88, np.nan],
    [np.nan, 76, 82],
    
    [95, 91, 89],
    [80, np.nan, np.nan]
])

nan_locations=np.isnan(marks)
print(nan_locations)

total_nan=np.sum(np.isnan(marks))
print(total_nan)

subject_mean=np.nanmean(marks, axis=0)
print(subject_mean)




cleaned_marks = marks.copy()
rows, cols = np.where(np.isnan(cleaned_marks))
cleaned_marks[rows, cols] = avg_col[cols]
print(cleaned_marks)



mask=np.sum(np.isnan(cleaned_marks), axis=1)==0
complete_students=cleaned_marks[mask]
print(complete_students)

avg=np.mean(complete_students, axis=0)
std_d=np.std(complete_students, axis=0)
normalized_marks=(complete_students-avg)/std_d
print(normalized_marks)




# Q1
# Why is np.mean() not suitable for datasets containing NaN values?
#Ans  because we mostly nedd and uses the mean by ignoring the nan values

# Q2
# Why is replacing missing values with the column mean usually better than replacing them with 0?
#Ans be cause when a model is trained on that data it will pridict more accurately .

# Q3
# In which situations would you remove rows containing NaN instead of filling them?
#Ans if the rows are duplicated or it do not have importent data and all not nesessory stuff is present and where only very very small amount of data is present so it is eiser to remove row instead of filling  

[[False  True False]
 [False False  True]
 [ True False False]
 [False False False]
 [False  True  True]]
5
[87.5 85.  83. ]
[[85.  85.  78. ]
 [90.  88.  83. ]
 [87.5 76.  82. ]
 [95.  91.  89. ]
 [80.  85.  83. ]]
[[95. 91. 89.]]
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]]


# NumPy ML Challenge 50: Invalid Data Detection & Correction

## Dataset

```python
import numpy as np

employees = np.array([
    [25, 170, 65, 50000],
    [-3, 180, 72, 60000],
    [30, 45, 80, -10000],
    [22, 175, 150, 45000],
    [40, 168, 70, 900000],
    [35, 172, 68, 55000]
], dtype=float)
```

### Columns

- Column 0 → Age (years)
- Column 1 → Height (cm)
- Column 2 → Weight (kg)
- Column 3 → Salary

---

## Valid Ranges

| Feature | Valid Range |
|----------|-------------|
| Age | 18 – 60 |
| Height | 100 – 220 cm |
| Weight | 30 – 150 kg |
| Salary | 20,000 – 200,000 |

---

## Tasks

### Task 1

Extract:

- `age`
- `height`
- `weight`
- `salary`

---

### Task 2

Detect invalid values using boolean masks.

Create:

```python
invalid_age
invalid_height
invalid_weight
invalid_salary
```

---

### Task 3

Count the number of invalid values in each column.

Store in:

```python
invalid_counts
```

---

### Task 4

Correct invalid values.

Rules:

- Age → Clip to **18–60**
- Height → Clip to **100–220**
- Weight → Clip to **30–150**
- Salary → Clip to **20000–200000**

Store in:

```python
cleaned_data
```

---

### Task 5

Normalize:

- Height
- Weight
- Salary

using the cleaned dataset.

Store in:

```python
normalized_features
```

---

### Task 6

Create a new feature:

```python
BMI
```

using the cleaned data.

---

## Conceptual Questions

### Q1

What is the difference between:

- Missing value
- Invalid value
- Outlier

---

### Q2

Why is clipping sometimes preferred over removing rows?

---

### Q3

Would you always clip invalid values in a real project? If not, when would you choose another approach?


In [63]:
employees = np.array([
    [25, 170, 65, 50000],
    [-3, 180, 72, 60000],
    [30, 45, 80, -10000],
    [22, 175, 150, 45000],
    [40, 168, 70, 900000],
    [35, 172, 68, 55000]
], dtype=float)

age=employees[:, 0]
height=employees[:, 1]
weight=employees[:, 2]
salary=employees[:, 3]
print(age)
print(height)
print(weight)
print(salary)

invalid_age = (age < 18) | (age > 60)
invalid_height= (height<100) | (height>220)
invalid_weight= (weight<30) | (weight>150)
invalid_salary= (salary<20000) | (salary>200000)

print(invalid_age)
print(invalid_height)
print(invalid_weight)
print(invalid_salary)


invalid_counts=(
    np.sum(invalid_age),
    np.sum(invalid_height),
    np.sum(invalid_weight),
    np.sum(invalid_salary))
print(invalid_counts)



cleaned_data =np.column_stack((
    np.clip(age, 18, 60), 
    np.clip(height, 100, 220), 
    np.clip(weight, 30, 150), 
    np.clip(salary, 20000, 200000)
))
print(cleaned_data)


normalized_features=(cleaned_data-np.mean(cleaned_data[1:], axis=0))/np.std(cleaned_data[1:], axis=0)
print(normalized_features)


clean_height = (cleaned_data[:, 1])
clean_weight = cleaned_data[:, 2]

bmi=clean_weight/((clean_height/100)**2)

print(bmi)

# Q1
# What is the difference between:

# Missing value == np.nan or null value
# Invalid value == the value which does not fits in the sutabale range of feature
# Outlier===
# Q2
# Why is clipping sometimes preferred over removing rows?
#ans  cliping takes 3 arguments (in which we have to make changes , ower limit , upper limit) it set the lower limit if the value is lower the the limit and vice versa

# Q3
# Would you always clip invalid values in a real project? If not, when would you choose another approach?
#ans no not alwayes , it depends on data type and its use also we can replace the nan with avrage with color data

[25. -3. 30. 22. 40. 35.]
[170. 180.  45. 175. 168. 172.]
[ 65.  72.  80. 150.  70.  68.]
[ 50000.  60000. -10000.  45000. 900000.  55000.]
[False  True False False False False]
[False False  True False False False]
[False False False False False False]
[False False  True False  True False]
(np.int64(1), np.int64(1), np.int64(0), np.int64(2))
[[2.50e+01 1.70e+02 6.50e+01 5.00e+04]
 [1.80e+01 1.80e+02 7.20e+01 6.00e+04]
 [3.00e+01 1.00e+02 8.00e+01 2.00e+04]
 [2.20e+01 1.75e+02 1.50e+02 4.50e+04]
 [4.00e+01 1.68e+02 7.00e+01 2.00e+05]
 [3.50e+01 1.72e+02 6.80e+01 5.50e+04]]
[[-0.4938648   0.36963568 -0.73560935 -0.40936   ]
 [-1.3581282   0.70566811 -0.51172824 -0.25191384]
 [ 0.1234662  -1.98259135 -0.25586412 -0.88169846]
 [-0.8642634   0.53765189  1.98294694 -0.48808307]
 [ 1.3581282   0.30242919 -0.57569427  1.95233229]
 [ 0.7407972   0.43684216 -0.6396603  -0.33063692]]
[22.49134948 22.22222222 80.         48.97959184 24.8015873  22.98539751]


# NumPy ML Challenge 51: Outlier Detection (Z-Score)

## Dataset

```python
import numpy as np

salary = np.array([
    45000,
    48000,
    50000,
    51000,
    52000,
    47000,
    49000,
    53000,
    900000,
    46000
], dtype=float)
```

---

## Tasks

### Task 1

Calculate:

- Mean
- Standard Deviation

Store in:

```python
mean_salary
std_salary
```

---

### Task 2

Calculate the Z-score for every salary.

Formula:

```text
(value - mean) / std
```

Store in:

```python
z_score
```

---

### Task 3

Detect all outliers.

Rule:

```python
abs(z_score) > 2
```

Store in:

```python
outlier_mask
```

---

### Task 4

Print only the outlier values.

Store in:

```python
outliers
```

---

### Task 5

Create a dataset **without** outliers.

Store in:

```python
clean_salary
```

---

### Task 6

Compare the statistics before and after removing outliers.

Calculate:

- Mean (before)
- Mean (after)
- Standard Deviation (before)
- Standard Deviation (after)

---

## Conceptual Questions

### Q1

Why does an outlier affect the mean more than the median?

---

### Q2

Would you always remove outliers before training an ML model? Explain.

---

### Q3

Give **three real-world examples** where outliers are expected and should not necessarily be removed.

In [11]:
salary = np.array([
    45000,
    48000,
    50000,
    51000,
    52000,
    47000,
    49000,
    53000,
    900000,
    46000
], dtype=float)


mean_salary=np.mean(salary)
std_salary=np.std(salary)
z_score=(salary-mean_salary)/std_salary
outlier_mask=abs(z_score)>2
outliers=salary[outlier_mask]
clean_salary=salary[~outlier_mask]
mean_salary_after=np.mean(clean_salary)
std_salary_after=np.std(clean_salary)




print(mean_salary)
print(std_salary)
print(z_score)
print(outliers)
print(clean_salary)
print("Mean (before)", mean_salary)
print("Mean (after)", mean_salary_after)
print("Standard Deviation (before)", std_salary)
print("Standard Deviation (after)", std_salary_after)




#Q1  because its calculation factors in the exact magnitude of every single data point.
#Q2 No, you should not always remove outliers blindly. Whether to remove them depends entirely on the context and the model.
#Q3 Fraud Detection, Medical Research, Seismology and Natural Disasters

134100.0
255311.7506108953
[-0.34898511 -0.33723477 -0.32940121 -0.32548443 -0.32156765 -0.34115155
 -0.33331799 -0.31765087  2.99986193 -0.34506833]
[900000.]
[45000. 48000. 50000. 51000. 52000. 47000. 49000. 53000. 46000.]
Mean (before) 134100.0
Mean (after) 49000.0
Standard Deviation (before) 255311.7506108953
Standard Deviation (after) 2581.9888974716114


# NumPy ML Challenge 52: Outlier Detection (IQR Method)

## Dataset

```python
import numpy as np

house_prices = np.array([
    250000,
    270000,
    290000,
    310000,
    330000,
    350000,
    370000,
    390000,
    410000,
    1200000
], dtype=float)
```

## Tasks

### Task 1

Calculate:

- Q1 (25th percentile)
- Q2 (Median)
- Q3 (75th percentile)

Store in:

```python
Q1
Q2
Q3
```

---

### Task 2

Calculate the Interquartile Range.

Formula:

```text
IQR = Q3 - Q1
```

Store in:

```python
IQR
```

---

### Task 3

Calculate the lower and upper bounds.

Formula:

```text
Lower Bound = Q1 - 1.5 × IQR

Upper Bound = Q3 + 1.5 × IQR
```

Store in:

```python
lower_bound
upper_bound
```

---

### Task 4

Detect outliers using a boolean mask.

Store in:

```python
outlier_mask
```

---

### Task 5

Extract:

```python
outliers
```

---

### Task 6

Create a dataset without outliers.

Store in:

```python
clean_prices
```

---

### Task 7

Compare:

- Mean before cleaning
- Mean after cleaning

---

## Conceptual Questions

### Q1

Why is the IQR method more robust than the Z-score method for skewed datasets?

---

### Q2

What do the 25th percentile and 75th percentile represent?

---

### Q3

Name two real-world datasets where the IQR method is generally preferred over the Z-score method.

In [16]:
house_prices = np.array([
    250000,
    270000,
    290000,
    310000,
    330000,
    350000,
    370000,
    390000,
    410000,
    1200000
], dtype=float)


Q1 = np.percentile(house_prices, 25)
Q2 = np.percentile(house_prices, 50)
Q3 = np.percentile(house_prices, 75)
IQR = Q3 - Q1
Lower_Bound = Q1 - 1.5 * IQR
Upper_Bound = Q3 + 1.5 * IQR
avg=np.mean(house_prices)
std_d=np.std(house_prices)
norm=(house_prices-avg)/std_d
outlier_mask=abs(norm>2)
outliers=house_prices[outlier_mask]
clean_prices=house_prices[~outlier_mask]






print(Q1)
print(Q2)
print(Q3)
print(IQR)
print(Lower_Bound)
print(Upper_Bound)
print(outlier_mask)
print(outliers)
print(clean_prices)
print("Mean (before)", avg)
print("Mean (after)", np.mean(clean_prices))
print("Standard Deviation (before)", std_d)
print("Standard Deviation (after)", np.std(clean_prices))




# Q1
# Why is the IQR method more robust than the Z-score method for skewed datasets?
#ans it does not rely on the mean and standard deviation
# Q2
# What do the 25th percentile and 75th percentile represent?
#ans 25th and 27th percentile represent the 25% and the 75% of the max of datarespectively

# Q3
# Name two real-world datasets where the IQR method is generally preferred over the Z-score method.
# ans  heavily skewed or non-normally distributed data

295000.0
340000.0
385000.0
90000.0
160000.0
520000.0
[False False False False False False False False False  True]
[1200000.]
[250000. 270000. 290000. 310000. 330000. 350000. 370000. 390000. 410000.]
Mean (before) 417000.0
Mean (after) 330000.0
Standard Deviation (before) 265557.90329041233
Standard Deviation (after) 51639.777949432224


# NumPy ML Challenge 53: Matrix Multiplication

## Dataset

```python
import numpy as np

X = np.array([
    [2, 3],
    [4, 5],
    [6, 7]
], dtype=float)

W = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=float)

bias = np.array([10, 20, 30], dtype=float)
```

### Shapes

- X → (3, 2)
- W → (2, 3)
- bias → (3,)

---

## Tasks

### Task 1

Print the shape of:

- X
- W
- bias

---

### Task 2

Perform matrix multiplication.

```python
output = X @ W
```

Store in:

```python
output
```

---

### Task 3

Add the bias using broadcasting.

Store in:

```python
final_output
```

---

### Task 4

Find:

- Maximum value in `final_output`
- Minimum value
- Mean value

---

### Task 5

Normalize `final_output`.

Formula:

```text
(x − mean) / std
```

Store in:

```python
normalized_output
```

---

## Conceptual Questions

### Q1

Why can't we multiply two matrices if their inner dimensions don't match?

---

### Q2

What is the shape of the result of:

```text
(5×10) @ (10×7)
```

---

### Q3

In machine learning, what do the matrices **X** and **W** usually represent?

In [22]:
X = np.array([
    [2, 3],
    [4, 5],
    [6, 7]
], dtype=float)

W = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=float)

bias = np.array([10, 20, 30], dtype=float)

print(np.shape(X))
print(np.shape(W))
print(np.shape(bias))

output= X @ W
print(output)

final_output=output+bias
print(final_output)


final_output_max=np.max(final_output)
final_output_min=np.min(final_output)
final_output_mean=np.mean(final_output)
print(final_output_max)
print(final_output_min)
print(final_output_mean)




normalized_output=(final_output-final_output_mean)/np.std(final_output)
print(normalized_output)



# Q1
# Why can't we multiply two matrices if their inner dimensions don't match?
#ans

# Q2
# What is the shape of the result of:
# (5×10) @ (10×7)== 5*7=35
#ans

# Q3
# In machine learning, what do the matrices X and W usually represent?
#ans 

(3, 2)
(2, 3)
(3,)
[[14. 19. 24.]
 [24. 33. 42.]
 [34. 47. 60.]]
[[24. 39. 54.]
 [34. 53. 72.]
 [44. 67. 90.]]
90.0
24.0
53.0
[[-1.49072293 -0.71965934  0.05140424]
 [-0.97668054  0.          0.97668054]
 [-0.46263815  0.71965934  1.90195684]]


# NumPy ML Challenge 54: Dot Product

## Dataset

```python
import numpy as np

student_1 = np.array([85, 90, 78, 92])
student_2 = np.array([88, 86, 80, 91])

weights = np.array([0.2, 0.3, 0.1, 0.4])
```

### Task 1

Calculate the dot product of:

```python
student_1
```

and

```python
student_2
```

Store in:

```python
similarity_score
```

---

### Task 2

Calculate the weighted score of:

```python
student_1
```

using

```python
weights
```

Store in:

```python
weighted_score
```

---

### Task 3

Calculate the weighted score of:

```python
student_2
```

Store in:

```python
weighted_score_2
```

---

### Task 4

Find which student has the higher weighted score.

Store in:

```python
better_student
```

The value should be either:

```python
"Student 1"
```

or

```python
"Student 2"
```

---

### Task 5

Normalize both students' scores using Z-score normalization.

Store in:

```python
student_1_norm

student_2_norm
```

---

### Task 6

Calculate the dot product again using the normalized vectors.

Store in:

```python
normalized_similarity
```

---

## Conceptual Questions

### Q1

What is the difference between:

- Element-wise multiplication (`*`)
- Dot product (`np.dot()` or `@`)

---

### Q2

Why is the dot product used to compute weighted scores?

---

### Q3

Give two machine learning algorithms that internally use dot products.

In [30]:
student_1 = np.array([85, 90, 78, 92])
student_2 = np.array([88, 86, 80, 91])

weights = np.array([0.2, 0.3, 0.1, 0.4])


similarity_score=np.dot(student_1, student_2)
print(similarity_score)


weighted_score = np.average(student_1, weights=weights)
print(weighted_score) 

weighted_score2 = np.average(student_2, weights=weights)
#or
weighted_score2=np.dot(student_1, weights)
print(weighted_score2) 



# better_student=np.max([weighted_score,weighted_score2])
# print(better_student)

if weighted_score > weighted_score2:
    better_student = "Student 1"
else:
    better_student = "Student 2"
print(better_student)



student_1_norm=(student_1-np.mean(student_1))/np.std(student_1)
student_2_norm=(student_2-np.mean(student_2))/np.std(student_2)
print(student_1_norm)
print(student_2_norm)

normalized_similarity=np.dot(student_1_norm,student_2_norm)
print(normalized_similarity)

29832
88.6
88.6
Student 2
[-0.23137241  0.69411722 -1.52705788  1.06431307]
[ 0.43495884 -0.06213698 -1.55342442  1.18060256]
3.4849319132880705


# NumPy ML Challenge 55: Covariance Matrix

## Dataset

```python
import numpy as np

students = np.array([
    [170, 65, 80],
    [175, 70, 85],
    [180, 75, 90],
    [165, 60, 78],
    [172, 68, 82],
    [178, 73, 88]
], dtype=float)
```

### Columns

- Column 0 → Height (cm)
- Column 1 → Weight (kg)
- Column 2 → Marks

---

## Tasks

### Task 1

Extract:

```python
height
weight
marks
```

---

### Task 2

Calculate the covariance matrix using:

```python
np.cov(...)
```

Store in:

```python
cov_matrix
```

> **Hint:** Each column is a feature.

---

### Task 3

Print the covariance between:

- Height & Weight
- Height & Marks
- Weight & Marks

---

### Task 4

Which pair of features has the highest positive covariance?

Store the answer in:

```python
highest_covariance_pair
```

Example:

```python
"Height & Weight"
```

---

### Task 5

Normalize the dataset (column-wise).

Store in:

```python
normalized_students
```

---

## Conceptual Questions

### Q1

What does a positive covariance indicate?

---

### Q2

Can two variables have a covariance close to zero but still have a relationship?

---

### Q3

Why is covariance alone not enough to measure the strength of a relationship?

In [49]:
students = np.array([
    [170, 65, 80],
    [175, 70, 85],
    [180, 75, 90],
    [165, 60, 78],
    [172, 68, 82],
    [178, 73, 88]
], dtype=float)


height=students[:,0]
weight=students[:,1]
marks=students[:,2]


print(height)
print(weight)
print(marks)

cov_matrix=np.cov(students.T)
print(cov_matrix)

cov_hw = np.cov(height, weight)[0,1]
cov_hm = np.cov(height, marks)[0,1]
cov_wm = np.cov(weight, marks)[0,1]
print(cov_hw)
print(cov_hm)
print(cov_wm)


if cov_hw > cov_hm and cov_hw > cov_wm:
    highest_covariance_pair = "Height & Weight"

elif cov_hm > cov_wm:
    highest_covariance_pair = "Height & Marks"

else:
    highest_covariance_pair = "Weight & Marks"

print(highest_covariance_pair)

normalized_students=(students-np.mean(students, axis=0))/np.std(students, axis=0)
print(normalized_students)

[170. 175. 180. 165. 172. 178.]
[65. 70. 75. 60. 68. 73.]
[80. 85. 90. 78. 82. 88.]
[[30.26666667 30.         25.26666667]
 [30.         29.9        24.9       ]
 [25.26666667 24.9        21.76666667]]
30.0
25.266666666666666
24.900000000000002
Height & Weight
[[-0.66372331 -0.70116959 -0.90005955]
 [ 0.33186166  0.30050125  0.27393117]
 [ 1.32744662  1.3021721   1.44792189]
 [-1.65930828 -1.70284044 -1.36965584]
 [-0.26548932 -0.10016708 -0.43046326]
 [ 0.92921264  0.90150376  0.9783256 ]]


# NumPy ML Challenge 56: Correlation Matrix

## Dataset

```python
import numpy as np

students = np.array([
    [170, 65, 80],
    [175, 70, 85],
    [180, 75, 90],
    [165, 60, 78],
    [172, 68, 82],
    [178, 73, 88]
], dtype=float)
```

### Columns

- Column 0 → Height (cm)
- Column 1 → Weight (kg)
- Column 2 → Marks

---

## Tasks

### Task 1

Extract:

```python
height
weight
marks
```

---

### Task 2

Calculate the correlation matrix.

Store in:

```python
corr_matrix
```

> Hint: Use `np.corrcoef()`.

---

### Task 3

Print the correlation between:

- Height & Weight
- Height & Marks
- Weight & Marks

---

### Task 4

Find the pair with the strongest positive correlation.

Store in:

```python
strongest_pair
```

Example:

```python
"Height & Weight"
```

---

### Task 5

Print:

- Maximum correlation value (excluding the diagonal)
- Minimum correlation value (excluding the diagonal)

---

## Conceptual Questions

### Q1

What does a correlation value of **+1**, **0**, and **−1** indicate?

---

### Q2

Why is correlation generally preferred over covariance when comparing relationships between features?

---

### Q3

If two features have a correlation of **0.98**, would you keep both features in a linear regression model? Why or why not?

In [53]:
students = np.array([
    [170, 65, 80],
    [175, 70, 85],
    [180, 75, 90],
    [165, 60, 78],
    [172, 68, 82],
    [178, 73, 88]
], dtype=float)

height=students[:,0]
weight=students[:,1]
marks=students[:,2]


print(height)
print(weight)
print(marks)



corr_matrix=np.corrcoef(students.T)
print(corr_matrix)

corr_hw = np.corrcoef(height, weight)[0,1]
corr_hm = np.corrcoef(height, marks)[0,1]
corr_wm = np.corrcoef(weight, marks)[0,1]
print(corr_hw)
print(corr_hm)
print(corr_wm)


if corr_hw > corr_hm and corr_hw > corr_wm:
    strongest_pair = "Height & Weight"

elif corr_hm > corr_wm:
    strongest_pair = "Height & Marks"

else:
    strongest_pair = "Weight & Marks"

print(strongest_pair)

corr_values = np.array([
    corr_hw,
    corr_hm,
    corr_wm
])

print(np.max(corr_values))
print(np.min(corr_values))

[170. 175. 180. 165. 172. 178.]
[65. 70. 75. 60. 68. 73.]
[80. 85. 90. 78. 82. 88.]
[[1.         0.99724844 0.98439566]
 [0.99724844 1.         0.97604039]
 [0.98439566 0.97604039 1.        ]]
0.9972484355063392
0.9843956609404761
0.9760403897011246
Height & Weight
0.9972484355063392
0.9760403897011246


# NumPy ML Challenge 57: Euclidean Distance

## Dataset

```python
import numpy as np

students = np.array([
    [170, 65],
    [175, 70],
    [180, 75],
    [165, 60],
    [172, 68]
], dtype=float)

new_student = np.array([173, 67], dtype=float)
```

### Columns

- Column 0 → Height (cm)
- Column 1 → Weight (kg)

---

## Tasks

### Task 1

Calculate the Euclidean distance between `new_student` and every student.

Store in:

```python
distances
```

---

### Task 2

Find the index of the nearest student.

Store in:

```python
nearest_index
```

---

### Task 3

Print the nearest student's data.

Store in:

```python
nearest_student
```

---

### Task 4

Find the farthest student.

Store in:

```python
farthest_index
farthest_student
```

---

### Task 5

Normalize the dataset (column-wise).

Also normalize `new_student` using the **same** mean and standard deviation.

Then calculate the Euclidean distances again.

Store in:

```python
normalized_distances
```

---

## Conceptual Questions

### Q1

Why is feature normalization important before calculating Euclidean distance?

---

### Q2

Which ML algorithm is most famous for using Euclidean distance?

---

### Q3

What would happen if one feature ranged from **1–10** while another ranged from **1–1,000,000**, and you did **not** normalize the data?

In [69]:
students = np.array([
    [170, 65],
    [175, 70],
    [180, 75],
    [165, 60],
    [172, 68]
], dtype=float)

new_student = np.array([173, 67], dtype=float)

distances = np.linalg.norm(students - new_student, axis=1)
print(distances)

nearest_index=np.argmin(distances)
print(nearest_index)

nearest_student=students[nearest_index]
print(nearest_student)

farthest_index=np.argmax(distances)
farthest_student=students[farthest_index]
print(farthest_index)
print(farthest_student)


mean = np.mean(students, axis=0)
std = np.std(students, axis=0)
norm_students = (students - mean) / std
norm_new_student = (new_student - mean) / std
normalized_distances = np.linalg.norm(norm_students - norm_new_student,axis=1)
print(normalized_distances)

[ 3.60555128  3.60555128 10.63014581 10.63014581  1.41421356]
4
[172.  68.]
2
[180.  75.]
[0.72053406 0.72053406 2.12433038 2.12433038 0.28261671]


# NumPy ML Challenge 58: Cosine Similarity

## Dataset

```python
import numpy as np

documents = np.array([
    [2, 1, 0, 3],
    [1, 0, 2, 2],
    [3, 2, 0, 4],
    [0, 1, 3, 1]
], dtype=float)

query = np.array([2, 1, 1, 3], dtype=float)
```

Each row represents a document embedding.

The query is a search embedding.

---

## Tasks

### Task 1

Calculate the cosine similarity between the query and every document.

Store in:

```python
similarities
```

---

### Task 2

Find the index of the most similar document.

Store in:

```python
best_match_index
```

---

### Task 3

Print the most similar document.

Store in:

```python
best_match
```

---

### Task 4

Find the least similar document.

Store in:

```python
least_match_index
least_match
```

---

### Task 5

Sort all documents from most similar to least similar.

Store in:

```python
sorted_indices
```

---

## Conceptual Questions

### Q1

Why is cosine similarity preferred over Euclidean distance for text embeddings?

---

### Q2

What is the range of cosine similarity?

---

### Q3

Give three real-world AI applications that use cosine similarity.

In [84]:
documents = np.array([
    [2, 1, 0, 3],
    [1, 0, 2, 2],
    [3, 2, 0, 4],
    [0, 1, 3, 1]
], dtype=float)

query = np.array([2, 1, 1, 3], dtype=float)

similarities=np.dot(documents, query)/(np.linalg.norm(documents, axis=1)*np.linalg.norm(query))
print(similarities)


best_match_index=np.argmax(similarities)
print(best_match_index)

best_match=documents[best_match_index]
print(best_match)

least_match_index=np.argmin(similarities)
least_match=documents[least_match_index]
print(least_match_index)
print(least_match)

sorted_indices=np.argsort(similarities)
print(sorted_indices[::-1])

[0.96609178 0.86066297 0.9589266  0.54494926]
0
[2. 1. 0. 3.]
3
[0. 1. 3. 1.]
[0 2 1 3]


# NumPy ML Challenge 59: Batch Matrix Operations

## Dataset

```python
import numpy as np

X = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [5, 7, 9],
    [4, 2, 8]
], dtype=float)

W = np.array([
    [0.2, 0.5],
    [0.4, 0.3],
    [0.6, 0.1]
], dtype=float)

bias = np.array([1.0, 2.0])
```

### Shapes

- X → (4,3)
- W → (3,2)
- bias → (2,)

---

## Tasks

### Task 1

Print the shapes of:

- X
- W
- bias

---

### Task 2

Compute the batch predictions.

Store in:

```python
predictions
```

Formula:

```text
X @ W
```

---

### Task 3

Add the bias using broadcasting.

Store in:

```python
final_predictions
```

---

### Task 4

For every sample, calculate:

- Maximum prediction
- Minimum prediction
- Mean prediction

Store in:

```python
sample_max
sample_min
sample_mean
```

---

### Task 5

Normalize the prediction matrix column-wise.

Store in:

```python
normalized_predictions
```

---

### Task 6

Find the sample with the highest average prediction.

Store in:

```python
best_sample_index
```

---

## Conceptual Questions

### Q1

Why do deep learning frameworks process data in batches instead of one sample at a time?

---

### Q2

If:

```text
X = (128 × 784)

W = (784 × 10)
```

What is the shape of:

```text
X @ W
```

---

### Q3

In machine learning, what do the rows and columns of matrix **X** usually represent?

In [87]:
X = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [5, 7, 9],
    [4, 2, 8]
], dtype=float)

W = np.array([
    [0.2, 0.5],
    [0.4, 0.3],
    [0.6, 0.1]
], dtype=float)

bias = np.array([1.0, 2.0])

print(np.shape(X))
print(np.shape(W))
print(np.shape(bias))

predictions=X@W
print(predictions)


final_predictions=predictions+bias
print(final_predictions)

sample_max = np.max(final_predictions, axis=1)
sample_min = np.min(final_predictions, axis=1)
sample_mean = np.mean(final_predictions, axis=1)

print("Maximum:", sample_max)
print("Minimum:", sample_min)
print("Mean:", sample_mean)


col_min = np.min(final_predictions, axis=0)
col_max = np.max(final_predictions, axis=0)

normalized_predictions = (final_predictions - col_min) / (col_max - col_min)

print(normalized_predictions)


best_sample_index = np.argmax(sample_mean)

print(best_sample_index)


(4, 3)
(3, 2)
(2,)
[[5.6 2.8]
 [4.4 1.9]
 [9.2 5.5]
 [6.4 3.4]]
[[ 6.6  4.8]
 [ 5.4  3.9]
 [10.2  7.5]
 [ 7.4  5.4]]
Maximum: [ 6.6  5.4 10.2  7.4]
Minimum: [4.8 3.9 7.5 5.4]
Mean: [5.7  4.65 8.85 6.4 ]
[[0.25       0.25      ]
 [0.         0.        ]
 [1.         1.        ]
 [0.41666667 0.41666667]]
2


# NumPy ML Challenge 60: Mini ML Preprocessing Project

## Dataset

```python
import numpy as np

X = np.array([
    [170, 65, 80],
    [175, 70, 85],
    [180, 75, 90],
    [165, 60, 78],
    [172, 68, 82]
], dtype=float)

W = np.array([
    [0.2, 0.5],
    [0.4, 0.3],
    [0.6, 0.1]
], dtype=float)

bias = np.array([1.0, 2.0])

query = np.array([173, 67, 84], dtype=float)
```

### Columns

- Column 0 → Height
- Column 1 → Weight
- Column 2 → Marks

---

## Tasks

### Task 1

Normalize `X` column-wise using Z-score normalization.

Store in:

```python
X_norm
```

---

### Task 2

Normalize the `query` using the **same** mean and standard deviation used for `X`.

Store in:

```python
query_norm
```

---

### Task 3

Calculate the Euclidean distance between `query_norm` and every normalized student.

Store in:

```python
distances
```

---

### Task 4

Find:

```python
nearest_index
nearest_student
```

---

### Task 5

Compute the batch prediction.

Formula:

```text
X @ W + bias
```

Store in:

```python
predictions
```

---

### Task 6

Normalize the prediction matrix column-wise using Z-score normalization.

Store in:

```python
normalized_predictions
```

---

### Task 7

Calculate the cosine similarity between the normalized query and every normalized student.

Store in:

```python
similarities
```

---

### Task 8

Find:

```python
most_similar_index
```

---

### Task 9

Print:

- Covariance matrix of `X`
- Correlation matrix of `X`

---

### Task 10

Print:

- Feature-wise mean
- Feature-wise standard deviation
- Feature-wise maximum
- Feature-wise minimum

---

## Conceptual Questions

### Q1

Why should the query always be normalized using the training dataset's mean and standard deviation instead of its own?

---

### Q2

When would Euclidean distance and cosine similarity choose different nearest neighbors?

---

### Q3

Name three preprocessing steps that should usually be completed before training a machine learning model.

In [101]:
X = np.array([
    [170, 65, 80],
    [175, 70, 85],
    [180, 75, 90],
    [165, 60, 78],
    [172, 68, 82]
], dtype=float)

W = np.array([
    [0.2, 0.5],
    [0.4, 0.3],
    [0.6, 0.1]
], dtype=float)

bias = np.array([1.0, 2.0])

query = np.array([173, 67, 84], dtype=float)

avg=np.mean(X, axis=0)
std=np.std(X, axis=0)
X_norm=(X-avg)/std
query_norm=(query-avg)/std
distances=np.linalg.norm(query_norm-X_norm, axis=1)
nearest_index=np.argmin(distances)
nearest_student=X[nearest_index]
predictions=(X @ W)+ bias
normalized_predictions=(predictions-np.mean(predictions, axis=0))/np.std(predictions, axis=0)
similarities=np.dot(X_norm,query_norm)/(np.linalg.norm(X_norm, axis=1)*np.linalg.norm(query_norm))
most_similar_index=np.argmax(similarities)
corr=np.corrcoef(X.T)
cov=np.cov(X.T)

print(X_norm)
print(query_norm)
print(distances)
print(nearest_index)
print(nearest_student)
print(predictions)
print(normalized_predictions)
print(similarities)
print(most_similar_index)
print(corr)
print(cov)



print(np.mean(X[:,0]))
print(np.mean(X[:,1]))
print(np.mean(X[:,2]))
print(np.std(X[:,0]))
print(np.std(X[:,1]))
print(np.std(X[:,2]))
print(np.max(X[:,0]))
print(np.max(X[:,1]))
print(np.max(X[:,2]))
print(np.min(X[:,0]))
print(np.min(X[:,1]))
print(np.min(X[:,2]))

[[-0.47961646 -0.5195845  -0.71509694]
 [ 0.5195845   0.47961646  0.47673129]
 [ 1.51878546  1.47881742  1.66855953]
 [-1.47881742 -1.51878546 -1.19182824]
 [-0.07993608  0.07993608 -0.23836565]]
[ 0.11990412 -0.11990412  0.23836565]
[1.19509842 0.75893841 2.56090494 2.56090494 0.55420658]
4
[172.  68.  82.]
[[109.  114.5]
 [115.  119. ]
 [121.  123.5]
 [104.8 110.3]
 [111.8 116.6]]
[[-0.60540412 -0.51682745]
 [ 0.48869971  0.50322673]
 [ 1.58280355  1.52328092]
 [-1.37127681 -1.46887803]
 [-0.09482233 -0.04080217]]
[-0.56312331  0.4747249   0.51006279 -0.39260823 -0.98464205]
2
[[1.         0.99680511 0.98128176]
 [0.99680511 1.         0.97175475]
 [0.98128176 0.97175475 1.        ]]
[[31.3  31.2  25.75]
 [31.2  31.3  25.5 ]
 [25.75 25.5  22.  ]]
172.4
67.6
83.0
5.0039984012787215
5.0039984012787215
4.1952353926806065
180.0
75.0
90.0
165.0
60.0
78.0
