# NumPy Practice Questions

### Topics Covered :- 
#### Core NumPy
1 Array creation

2 Indexing & slicing

3 Reshaping

4 Broadcasting

5 Arithmetic

6 Statistics

7 Boolean masking

8 Sorting

9 Random module
#### Intermediate
1 Views vs copies

2 Axis operations

3 Stack & split

4 Matrix multiplication

5 Linear algebra

6 Eigenvalues

7 Determinants

8 Inverse matrices
#### Advanced
1 Missing values

2 clip()

3 maximum() / minimum()

4 take()

5 put()

6 .T

7 transpose()

8 diag()

9 trace()

10 matrix_rank()

11 ix_()

12 take_along_axis()

In [2]:
import numpy as np

## Q1. Array Creation — Properties

**Question:** Create a 1-D NumPy array `[10, 20, 30, 40, 50]` and print its **values**, **shape**, **dtype**, and **number of dimensions** (`ndim`).

In [3]:
array=np.array([10, 20, 30, 40, 50])
print(array)
print(array.shape)
print(array.dtype)
print(array.ndim)


[10 20 30 40 50]
(5,)
int64
1


## Q2. 1-D Indexing & Slicing

**Question:** Given `arr = [5, 10, 15, 20, 25, 30]`, print:
- The **first** element
- The **last** element
- Elements from index **1 to 4** (exclusive)
- Every **second** element starting at index 0
- Every second element using step-only syntax
- The array **reversed**

In [11]:
arr=np.array([5, 10, 15, 20, 25, 30])
print(arr[0])
print(arr[len(arr)-1])
print(arr[1:5])
print(arr[0:5:2])
print(arr[::2])

5
30
[10 15 20 25]
[ 5 15 25]
[ 5 15 25]


## Q3. 2-D Array Indexing

**Question:** Create a 3×3 matrix `[[1,2,3],[4,5,6],[7,8,9]]` and print:
- The element at **row 1, col 1**
- The element at **row 2, col 2**
- The entire **second row**
- The entire **third column**

In [5]:
arr=np.array([[1,2,3],
              [4,5,6,],
              [7,8,9]])
print(arr[1,1])
print(arr[2,2])
print(arr[1])
print(arr[:,2])

5
9
[4 5 6]
[3 6 9]


## Q4. Reshape & Flatten

**Question:** Create `arr = [10, 20, 30, 40, 50, 60]`. Reshape it to shape **(2, 3)**, print the reshaped array and its shape, then **flatten** it back to 1-D.

In [6]:
arr=np.array([10,20,30,40,50,60])
arr_reshpe=arr.reshape(2,3)
print(arr_reshpe)
print(arr_reshpe.shape)
arr_flatten=arr_reshpe.flatten()
print(arr_flatten)

[[10 20 30]
 [40 50 60]]
(2, 3)
[10 20 30 40 50 60]


## Q5. Statistical Functions

**Question:** Given `arr = [12, 15, 18, 20, 25]`, compute and print the **sum**, **mean**, **median**, **minimum**, and **maximum**.

In [7]:
arr=np.array([[12, 15, 18, 20, 25]])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))

90
18.0
18.0
12
25


## Q6. Boolean Masking

**Question:** Given `numbers = [5, 12, 8, 20, 15, 3, 25]`, use boolean masks to extract:
- Numbers **greater than 10**
- **Even** numbers
- Numbers **less than 15**

In [8]:
numbers=np.array([[5, 12, 8, 20, 15, 3, 25]])
mask=numbers>10
even=numbers%2==0
less_than_15=numbers<15
# print(numbers[numbers>10])
print(numbers[mask])
print(numbers[even])
print(numbers[less_than_15])

[12 20 15 25]
[12  8 20]
[ 5 12  8  3]


## Q7. arange & linspace

**Question:** - Create integers **0 to 9** using `np.arange`
- Create **5 evenly spaced floats** from 10 to 50 using `np.linspace`
- Create **5 evenly spaced floats** from 0 to 100 using `np.linspace`

In [10]:
arr1=np.arange(0,10)
print(arr1)
arr2=np.linspace(10,50,5)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[10. 20. 30. 40. 50.]


## Q8. Broadcasting — Scalar Operations

**Question:** Given `a = [10, 20, 30, 40]`, create and print:
- `a + 5` (add 5 to each element)
- `a * 2` (multiply each element by 2)
- `a / 10` (divide each element by 10)

In [10]:
a = np.array([10, 20, 30, 40])
print("a + 5  :", a + 5)
print("a * 2  :", a * 2)
print("a / 10 :", a / 10)


a + 5  : [15 25 35 45]
a * 2  : [20 40 60 80]
a / 10 : [1. 2. 3. 4.]


## Q9. Element-wise Array Operations

**Question:** Given `a = [1, 2, 3, 4]` and `b = [10, 20, 30, 40]`, compute and print element-wise **addition**, **subtraction**, **multiplication**, and **division**.

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
add=a+b
sub=a-b
mul=a*b
div=a/b
print(add)
print(sub)
print(mul)
print(div)


[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]


## Q10. Axis-wise Summation

**Question:** Create `arr = [1, 2, 3, 4, 5, 6]`, reshape it to **(2, 3)**, then compute:
- **Column-wise sum** (axis=0)
- **Row-wise sum** (axis=1)

In [13]:
arr = np.array([1,2,3,4,5,6])
arr_reshape=arr.reshape(2,3)
print(arr_reshape)
sum_col=np.sum(arr_reshape, axis=0)
print(sum_col)
sum_row=np.sum(arr_reshape, axis=1)
print(sum_row)

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


## Q11. Sorting & Unique Values

**Question:** Given `arr = [5, 2, 8, 2, 9, 1, 5]`, print:
- The array **sorted in ascending order**
- The **argsort** (indices that would sort the array)
- The **unique** values

In [14]:
arr = np.array([5, 2, 8, 2, 9, 1, 5])
print("Sorted         :", np.sort(arr))
print("Argsort indices:", np.argsort(arr))
print("Unique values  :", np.unique(arr))


Sorted         : [1 2 2 5 5 8 9]
Argsort indices: [5 1 3 0 6 2 4]
Unique values  : [1 2 5 8 9]


## Q12. Random Arrays — randint, shuffle, seed, rand

**Question:** - Generate **5 random integers** between 1 and 9
- **Shuffle** the array in-place
- Use **seed(42)** for reproducibility
- Generate **3 random floats** between 0 and 1

In [15]:
np.random.seed(42)                      # for reproducible output
arr = np.random.randint(1, 10, 5)
print("Random integers (seed 42):", arr)

np.random.shuffle(arr)
print("After shuffle             :", arr)

arr_rand = np.random.rand(3)
print("3 random floats [0,1)     :", arr_rand)


Random integers (seed 42): [7 4 8 5 7]
After shuffle             : [7 7 5 8 4]
3 random floats [0,1)     : [0.45924889 0.33370861 0.14286682]


## Q13. Concatenation — concatenate, hstack, vstack

**Question:** - Horizontally join 1-D arrays `a=[1,2,3]` and `b=[4,5,6]` using `concatenate` and `hstack`
- Vertically stack 2-D arrays `c=[[1,2],[3,4]]` and `d=[[5,6],[7,8]]` using `vstack`

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("concatenate     :", np.concatenate((a, b)))
print("hstack          :", np.hstack((a, b)))

c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
print("vstack:\n", np.vstack((c, d)))


concatenate     : [1 2 3 4 5 6]
hstack          : [1 2 3 4 5 6]
vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Q14. np.where — Finding Indices

**Question:** Given `arr = [10, 20, 30, 40, 50]`:
- Find the **indices** where `arr > 25`
- Print the **values** at those indices
- Find indices where the value is **divisible by 20**

In [17]:
arr = np.array([10, 20, 30, 40, 50])
print("Indices where arr > 25      :", np.where(arr > 25))
print("Values where arr > 25       :", arr[arr > 25])
print("Indices divisible by 20     :", np.where(arr % 20 == 0))


Indices where arr > 25      : (array([2, 3, 4]),)
Values where arr > 25       : [30 40 50]
Indices divisible by 20     : (array([1, 3]),)


## Q15. Matrix Multiplication — dot vs @

**Question:** Given `A = [[1,2],[3,4]]` and `B = [[5,6],[7,8]]`, compute the matrix product using both `np.dot()` and the `@` operator, then verify they are equal.

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)
matmul      = A @ B

print("np.dot(A, B):\n", dot_product)
print("A @ B       :\n", matmul)
print("Both equal  :\n", dot_product == matmul)


np.dot(A, B):
 [[19 22]
 [43 50]]
A @ B       :
 [[19 22]
 [43 50]]
Both equal  :
 [[ True  True]
 [ True  True]]


## Q16. Determinant & Inverse

**Question:** Given `A = [[4,7],[2,6]]`, compute and print:
- The **determinant** using `np.linalg.det`
- The **inverse** using `np.linalg.inv`
- Verify by multiplying `A @ A_inv` (should give the identity matrix)

In [19]:
A = np.array([[4, 7],
              [2, 6]])
det = np.linalg.det(A)
inv = np.linalg.inv(A)
identity_check = A @ inv

print("Determinant      :", round(det, 4))
print("Inverse:\n", inv)
print("A @ A_inv (≈ I):\n", np.round(identity_check, 4))


Determinant      : 10.0
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A @ A_inv (≈ I):
 [[ 1. -0.]
 [ 0.  1.]]


## Q17. Eigenvalues & Eigenvectors

**Question:** Given `A = [[4,2],[1,3]]`, compute and print the **eigenvalues** and **eigenvectors** using `np.linalg.eig`.

In [20]:
A = np.array([[4, 2],
              [1, 3]])
values, vectors = np.linalg.eig(A)
print("Eigenvalues :", values)
print("Eigenvectors:\n", vectors)


Eigenvalues : [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


## Q18. Column-wise Normalisation

**Question:** Given a dataset of [height, weight] rows, compute:
- **Column mean** and **column std**
- **Normalised data** (Z-score normalisation column-wise)

In [21]:
data = np.array([[170, 65],
                 [180, 80],
                 [175, 75],
                 [160, 55]])

avg_col = np.mean(data, axis=0)
std_col = np.std(data, axis=0)
norm    = (data - avg_col) / std_col

print("Column mean        :", avg_col)
print("Column std         :", std_col)
print("Normalised data:\n", np.round(norm, 4))


Column mean        : [171.25  68.75]
Column std         : [7.39509973 9.60143218]
Normalised data:
 [[-0.169  -0.3906]
 [ 1.1832  1.1717]
 [ 0.5071  0.6509]
 [-1.5213 -1.4321]]


## Q19. Train / Test Split

**Question:** Create `data = np.arange(1, 21)` (20 elements). Split it so the **first 16** elements become training data and the **last 4** become test data, using both slicing and `np.split`.

In [22]:
data = np.arange(1, 21)
# Method 1 — slicing
train_slice = data[:16]
test_slice  = data[16:]
print("Train (slicing):", train_slice)
print("Test  (slicing):", test_slice)

# Method 2 — np.split
train, test = np.split(data, [16])
print("Train (split)  :", train)
print("Test  (split)  :", test)


Train (slicing): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Test  (slicing): [17 18 19 20]
Train (split)  : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Test  (split)  : [17 18 19 20]


## Q20. Dataset Analysis — Height & Weight

**Question:** Given a 5-row dataset of `[height, weight]`:
1. Compute **mean per column**
2. Find the **max per column**
3. Filter rows where **weight > 70**
4. **Sort rows** by height (ascending)
5. **Z-score normalise** column-wise

In [23]:
data = np.array([[170, 65],
                 [180, 80],
                 [175, 75],
                 [160, 55],
                 [185, 90]])

print("Mean per column          :", np.mean(data, axis=0))
print("Max  per column          :", np.max(data, axis=0))
print("Rows where weight > 70:\n", data[data[:, 1] > 70])

idx         = np.argsort(data[:, 0])
sorted_data = data[idx]
print("Sorted by height:\n", sorted_data)

norm = (data - np.mean(data, axis=0)) / np.std(data, axis=0)
print("Z-score normalised:\n", np.round(norm, 4))


Mean per column          : [174.  73.]
Max  per column          : [185  90]
Rows where weight > 70:
 [[180  80]
 [175  75]
 [185  90]]
Sorted by height:
 [[160  55]
 [170  65]
 [175  75]
 [180  80]
 [185  90]]
Z-score normalised:
 [[-0.465  -0.6621]
 [ 0.6975  0.5793]
 [ 0.1162  0.1655]
 [-1.6275 -1.4897]
 [ 1.2787  1.4069]]


## Q21. Employee Dataset Analysis

**Question:** Given `data = [[age, salary], ...]` for 5 employees:
1. Print **average age** and **average salary**
2. Find the **person with the highest salary** (print their row)
3. Print all rows where **age > 25**
4. **Sort** the dataset by salary (ascending)

In [24]:
data = np.array([[22,  50000],
                 [25,  60000],
                 [30,  80000],
                 [35, 120000],
                 [28,  75000]])

print("Average Age   :", np.mean(data[:, 0]))
print("Average Salary:", np.mean(data[:, 1]))

highest_idx = np.argmax(data[:, 1])
print("Highest Salary Row:", data[highest_idx])

print("Age > 25:\n", data[data[:, 0] > 25])

sorted_data = data[np.argsort(data[:, 1])]
print("Sorted by Salary:\n", sorted_data)


Average Age   : 28.0
Average Salary: 77000.0
Highest Salary Row: [    35 120000]
Age > 25:
 [[    30  80000]
 [    35 120000]
 [    28  75000]]
Sorted by Salary:
 [[    22  50000]
 [    25  60000]
 [    28  75000]
 [    30  80000]
 [    35 120000]]


## Q22. Handling NaN Values

**Question:** Given `marks = [85, NaN, 78, 92, NaN, 88]`:
1. Print the array with NaNs
2. **Detect** which positions are NaN using `np.isnan`
3. Compute the **mean ignoring NaNs** using `np.nanmean`
4. **Replace NaNs** with the mean using `np.nan_to_num`

In [25]:
marks = np.array([85, np.nan, 78, 92, np.nan, 88])
print("Original array  :", marks)
print("Is NaN mask     :", np.isnan(marks))

mean_no_nan = np.nanmean(marks)
print("Mean (ignore NaN):", mean_no_nan)

filled = np.nan_to_num(marks, nan=mean_no_nan)
print("NaNs replaced   :", filled)


Original array  : [85. nan 78. 92. nan 88.]
Is NaN mask     : [False  True False False  True False]
Mean (ignore NaN): 85.75
NaNs replaced   : [85.   85.75 78.   92.   85.75 88.  ]


## Q23. Clipping Values — np.clip

**Question:** Given `scores = [-20, 45, 110, 80, 150, 60, -5]`, **clip** all values to the range **[0, 100]** and print the clipped array. Verify the original is unchanged.

In [26]:
scores = np.array([-20, 45, 110, 80, 150, 60, -5])
print("Original :", scores)

clipped = np.clip(scores, 0, 100)
print("Clipped  :", clipped)
print("Original unchanged:", scores)  # np.clip returns a new array


Original : [-20  45 110  80 150  60  -5]
Clipped  : [  0  45 100  80 100  60   0]
Original unchanged: [-20  45 110  80 150  60  -5]


## Q24. Element-wise Maximum & Minimum

**Question:** Given `a = [5, 12, 8, 20, 15]` and `b = [10, 10, 10, 10, 10]`:
- Compute **element-wise maximum** using `np.maximum`
- Compute **element-wise minimum** using `np.minimum`
- Enforce a **floor of 10** on `a` using both `np.clip` and `np.where`

In [27]:
a = np.array([5, 12, 8, 20, 15])
b = np.array([10, 10, 10, 10, 10])

print("Element-wise max        :", np.maximum(a, b))
print("Element-wise min        :", np.minimum(a, b))
print("Floor 10 via clip       :", np.clip(a, 10, np.max(a)))
print("Floor 10 via np.where   :", np.where(a < 10, 10, a))


Element-wise max        : [10 12 10 20 15]
Element-wise min        : [ 5 10  8 10 10]
Floor 10 via clip       : [10 12 10 20 15]
Floor 10 via np.where   : [10 12 10 20 15]


## Q25. Selecting Elements — np.take

**Question:** Given `arr = [100, 200, 300, 400, 500, 600]`, use `np.take` to:
- Select elements at indices **0, 2, 5**
- Select elements at indices **1 and 4**

In [28]:
arr = np.array([100, 200, 300, 400, 500, 600])
print("Indices 0, 2, 5  :", np.take(arr, [0, 2, 5]))
print("Indices 1, 4     :", np.take(arr, [1, 4]))


Indices 0, 2, 5  : [100 300 600]
Indices 1, 4     : [200 500]


## Q26. Putting Values — np.put

**Question:** Given `arr = [10, 20, 30, 40, 50, 60]`, use `np.put` to:
- Replace indices **1 and 4** with **200 and 500**
- Then replace index **0** with **999**
- Print the array after each operation

In [28]:
arr = np.array([10, 20, 30, 40, 50, 60])
np.put(arr, [1, 4], [200, 500])
print("After put [1,4] → [200,500]:", arr)

np.put(arr, [0], [999])
print("After put [0]   → [999]    :", arr)


After put [1,4] → [200,500]: [ 10 200  30  40 500  60]
After put [0]   → [999]    : [999 200  30  40 500  60]


## Q27. Matrix Transpose

**Question:** Create matrix `A = [[1,2,3],[4,5,6]]` (shape 2×3).
- Print `A`, its **transpose** using `.T`, and using `np.transpose()`
- Print the shape of both `A` and its transpose

In [29]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print("A:\n", A)
print("A.T:\n", A.T)
print("np.transpose(A):\n", np.transpose(A))
print("Shape of A           :", A.shape)
print("Shape of A.T         :", A.T.shape)


A:
 [[1 2 3]
 [4 5 6]]
A.T:
 [[1 4]
 [2 5]
 [3 6]]
np.transpose(A):
 [[1 4]
 [2 5]
 [3 6]]
Shape of A           : (2, 3)
Shape of A.T         : (3, 2)


## Q28. Diagonal Extraction & Construction

**Question:** - Given a 3×3 matrix, extract its **main diagonal** using `np.diag`
- Create a **diagonal matrix** from `[10, 20, 30, 40]` using `np.diag`

In [30]:
A = np.array([[5, 2, 1],
              [7, 8, 3],
              [4, 6, 9]])
print("Matrix A:\n", A)
print("Main diagonal       :", np.diag(A))

diag_matrix = np.diag([10, 20, 30, 40])
print("Diagonal matrix:\n", diag_matrix)


Matrix A:
 [[5 2 1]
 [7 8 3]
 [4 6 9]]
Main diagonal       : [5 8 9]
Diagonal matrix:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


## Q29. Trace — Sum of Diagonal

**Question:** Given matrix `A = [[4,2,1],[0,5,3],[7,8,6]]`:
- Extract the **diagonal**
- Compute the **trace** using `np.trace`
- Verify that `trace == sum of diagonal`

In [31]:
A = np.array([[4, 2, 1],
              [0, 5, 3],
              [7, 8, 6]])
diag  = np.diag(A)
trace = np.trace(A)
print("Diagonal     :", diag)
print("np.trace(A)  :", trace)
print("diag.sum()   :", diag.sum())
print("Equal?       :", trace == diag.sum())


Diagonal     : [4 5 6]
np.trace(A)  : 15
diag.sum()   : 15
Equal?       : True


## Q30. Matrix Rank

**Question:** Compute the **rank** of two matrices:
- `A = [[1,2],[2,4]]` (linearly dependent rows — rank 1)
- `B = [[1,2],[3,4]]` (linearly independent — rank 2)
- Print whether they have equal rank

In [32]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[1, 2], [3, 4]])

rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)

print("Rank of A:", rank_A)
print("Rank of B:", rank_B)
print("Equal rank?", rank_A == rank_B)


Rank of A: 1
Rank of B: 2
Equal rank? False


## Q31. Submatrix Extraction — np.ix_

**Question:** Given a 4×4 matrix, extract a **2×2 submatrix** formed by rows [0, 2] and columns [1, 3] using `np.ix_`.

In [33]:
A = np.array([[11, 12, 13, 14],
              [21, 22, 23, 24],
              [31, 32, 33, 34],
              [41, 42, 43, 44]])
print("Full matrix:\n", A)

rows = [0, 2]
cols = [1, 3]
sub_matrix = A[np.ix_(rows, cols)]
print("Submatrix (rows 0,2 | cols 1,3):\n", sub_matrix)


Full matrix:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
Submatrix (rows 0,2 | cols 1,3):
 [[12 14]
 [32 34]]


## Q32. Row-wise Sorting — argsort + take_along_axis

**Question:** Given `A = [[30,10,20],[60,40,50]]`, sort each **row independently** in ascending order using `np.argsort` and `np.take_along_axis`.

In [34]:
A = np.array([[30, 10, 20],
              [60, 40, 50]])
print("Original:\n", A)

idx           = np.argsort(A, axis=1)         # sort indices per row
sorted_array  = np.take_along_axis(A, idx, axis=1)  # reorder using those indices
print("Argsort indices:\n", idx)
print("Row-wise sorted:\n", sorted_array)


Original:
 [[30 10 20]
 [60 40 50]]
Argsort indices:
 [[1 2 0]
 [1 2 0]]
Row-wise sorted:
 [[10 20 30]
 [40 50 60]]



## End of NumPy Practice 
